spring.application.name=ride-service
server.port=8083

spring.data.mongodb.uri=mongodb://localhost:27017/ridelink_rides
spring.data.mongodb.auto-index-creation=true

# Interservice URLs
services.driver-url=http://localhost:8082
services.fare-url=http://localhost:8084

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.com.ride_service=INFO
